sudo: required
services:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD) # This get the sha in latest commit
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1 # Disable all prompts during deployment
before_install:
  - openssl aes-256-cbc -K $encrypted_0c35eebf403c_key -iv $encrypted_0c35eebf403c_iv -in service-account.json.enc -out service-account.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json
### If you have to ever run/create different cluster, you have to run this command
  - gcloud config set project k8s-tutorial-233417
  - gcloud config set compute/zone asia-east2-a	
  - gcloud container clusters get-credentials multi-cluster
####
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  # - docker build -t stephengrider/react-test -f ./client/Dockerfile.dev ./client/Dockerfile.dev

script:
  - docker run stephengrider/react-test npm test -- --coverage

deploy:
  provider: script
  script: bash ./deploy.sh
  on: 
    branch: master