apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata: 
  name: k8s-multi-com-tls
spec:
  secretName: karuchicken-com
  issueRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: karuchicken.com
  dnsNames:
    - karuchicken.com
    - www.karuchicken.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - karuchicken.com
          - www.karuchicken.com